# 
GET http://localhost:3000/api/users

###


// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Test Testsson",
  "email": "test@mail.com",
  "password": "test"
}

###



// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "fruderic@mail.com",
  "password": "test"
}

###

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/ // ID PÅ PRODUKT

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt 1",
  "description": "Beskrivning av produkt 1",
  "price": 100, 
  "lager": 10
}

###